name: Service Build & Deploy
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: ['WarshipService/**']

jobs:
  Build: 
    permissions:
      actions: read
      contents: read
      id-token: write  
    uses: CombatWarships/DevOps/.github/workflows/BuildAndDeploy.yml@main
    with:
      CONTAINER_NAME: warshipregistry
      DOCKER_PATH: "./WarshipService/Dockerfile"
    secrets: inherit
